### ISSUE TITLE
Export Ontology dialog doesn't remember last location

### ISSUE THREAD

**Issue by nicholascar** [obdasystems/eddy#145]
If I export out an ontology, the next time I export, the Eddy Export Ontology dialog doesn't remember where I last exported to.

**Comment by mnamici** [comment]
Hi, thanks for the report. I think this is an easy enhancement that could be addressed before the next release. I'll assign myself and report back once we have a proposed implementation that can be tested.

**Comment by mnamici** [comment]
An implementation  for this feature has been merged. To keep things simple this is currently done in a generic way so that the last browsed folder is always saved and restored, without distinction between the specific action (open, export ecc...).  Feel free to reopen if you have feedback or find issues with the current implementation.

Test builds will be available [here](https://github.com/obdasystems/eddy/actions/runs/1218005840) once completed.

**Comment by nicholascar** [comment]
Sounds good, thanks!
