### ISSUE TITLE
Data Property instances

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/eddy#25]
Disallow incorrect ordering of input edges when the pair of individual nodes are an instance of an attribute.

For a pair of individual nodes, if they are an instance of an attribute, the first input edge connecting the respective node to the Property assertion node should be of type (individual) and the second one should be (Value).

The above property should hold even when the type is switched i.e. under all scenarios.

**Comment by mnamici** [comment]
Currently this has been fixed by disabling the switch to value toggle on individuals connected as subjects to a DataPropertyAssertion and only allowing to connect value nodes after having connected the DataPropertyAssertion subject. Existing diagrams containing literals as subjects will have to be fixed manually though.
