### ISSUE TITLE
[Q]: Problem installing PyQt5

### ISSUE THREAD

**Issue by milkbread** [obdasystems/eddy#257]
### Question

As this is not eddy-specific bug...I'll report it as question...hope this is ok :)

Beside the described syntax `pip install PyQt5 >= 5.8` which doesn't work at my shell...I need to do it this way: `pip install "PyQt5>=5.8"`...I had the same problem during installation of PyQt5, as it is already discussed [here](https://stackoverflow.com/questions/66546886/pip-install-stuck-on-preparing-wheel-metadata-when-trying-to-install-pyqt5)

I solved it by upgrading pip: `python -m pip install --upgrade pip`

Maybe it would be a good idea, to indicate on that possible problem? Especially, waiting for "Preparing wheel metadata ..." can be endless and senseless time consuming ;)

**Comment by mnamici** [comment]
About the syntax of the command in the documentation that is indeed a mistake as quotes are needed otherwise the shell interprets `>` as a redirection. I'll fix as soon as I can, thanks for pointing it out.
BTW the documentation is a bit outdated since as of v3.3 the minimum pyqt5 version supported is 5.11.

About the installation problem with pyqt5 I never actually stumbled upon the issue, looks like anytime for whatever reason pip tries to build the pyqt5 wheel from source the process gets stuck at the license agreement prompt.  
The workaround you point out works in some cases, however the issue still remains for users trying to install pyqt5 on platforms for which there are really no pre-built wheels available from pypi.org (e.g. for aarch64 linux distros). To me this looks more of a pyqt5 issue, and general instructions on how to build pyqt5 wheel from source are outside the scope of Eddy's installation instructions, but we can indeed add a warning for users that points out the issue. Thanks.
