### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by koslambrou** [obdasystems/eddy#90]
Are there any plans to publish this software to PyPI in order to install Eddy through a simple 
`pip install eddy` ?

**Comment by mnamici** [comment]
Hi @koslambrou, there are plans to publish Eddy to PyPI, however there are still a few issues that need to be sorted out in order to have a reliable installation via `pip`, like better support for using (or the lack of) an external JVM. 
There is also another unrelated project named `eddy` on PyPI which could cause confusion (although it looks abandoned), so we should come up with a different name.

In the meantime you should be able to install Eddy using `pip` directly from GitHub:
```sh
$ pip install PyQt5 # since its not listed in setup.py
$ pip install https://github.com/obdasystems/eddy/archive/master.zip
```

**Comment by koslambrou** [comment]
Hi @mnamici, the installation was successful. However, when launching `eddy`, there's the following error:

```
Traceback (most recent call last):
  File ".../eddy-1.2.0/.venv/bin/eddy", line 11, in <module>
    load_entry_point('Eddy==1.2.0', 'gui_scripts', 'eddy')()
TypeError: main() missing 1 required positional argument: 'args'
```

Should we change the `main` signature to `def main(args=None)` ?

**Comment by mnamici** [comment]
My bad, I forgot that the auto-generated script won't provide arguments to the called function (it's actually a documented behaviour). Unfortunately setting a default value of `None` won't be enough, since we need at least the executable name in the list, plus we won't be able to parse command line arguments anyway when launched from the script.

I guess the safest solution is to simply use `sys.argv` directly. It should be fixed in the latest master.
